// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqUCXNiFBwldNnLXs0LVPM0jnfLNiN_RA',
    appId: '1:993362533444:web:ef35cd5888d9b7ffd47011',
    messagingSenderId: '993362533444',
    projectId: 'rpg-p1',
    authDomain: 'rpg-p1.firebaseapp.com',
    storageBucket: 'rpg-p1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqUCXNiFBwldNnLXs0LVPM0jnfLNiN_RA',
    appId: '1:993362533444:android:ef35cd5888d9b7ffd47011',
    messagingSenderId: '993362533444',
    projectId: 'rpg-p1',
    storageBucket: 'rpg-p1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUCXNiFBwldNnLXs0LVPM0jnfLNiN_RA',
    appId: '1:993362533444:ios:ef35cd5888d9b7ffd47011',
    messagingSenderId: '993362533444',
    projectId: 'rpg-p1',
    storageBucket: 'rpg-p1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUCXNiFBwldNnLXs0LVPM0jnfLNiN_RA',
    appId: '1:993362533444:macos:ef35cd5888d9b7ffd47011',
    messagingSenderId: '993362533444',
    projectId: 'rpg-p1',
    storageBucket: 'rpg-p1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqUCXNiFBwldNnLXs0LVPM0jnfLNiN_RA',
    appId: '1:993362533444:windows:ef35cd5888d9b7ffd47011',
    messagingSenderId: '993362533444',
    projectId: 'rpg-p1',
    storageBucket: 'rpg-p1.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCqUCXNiFBwldNnLXs0LVPM0jnfLNiN_RA',
    appId: '1:993362533444:linux:ef35cd5888d9b7ffd47011',
    messagingSenderId: '993362533444',
    projectId: 'rpg-p1',
    storageBucket: 'rpg-p1.firebasestorage.app',
  );
}
